export const GET_FLIGHT_DETAILS = 'get_flight_details'
export const CURRENT_LOCATION_NOT_ENABLED = 'location_not_enabled'
export const SET_CURRENT_LOCATION = 'set_current_location'
export const SET_DESTINATION_LOCATION = 'set_destination_location'
export const COULD_NOT_FIND_FLIGHT = 'count_not_find_flight'
export const UPDATE_FLIGHT_DETAILS = 'update_flight_details'
export const START_LOADING = 'start_loading'
export const STOP_LOADING = 'stop_loading'
